// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ygkvxsapnlkotaruffjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlna3Z4c2Fwbmxrb3RhcnVmZmp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0ODQ3MjIsImV4cCI6MjA3MjA2MDcyMn0.Q7PRu-jDD5GFjl6NDHAZQPRzIVbAAwJGblkVqxLdX_Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});